name: Mirror to GitHub repository

on:
  push:
    branches: [release]
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://laze:${{ secrets.USER_TOKEN }}@github.com/elementary-interactive/neon-model-uuid-dev"
          source_branch: "release"
          destination_repo: "https://laze:${{ secrets.USER_TOKEN }}@github.com/elementary-interactive/neon-model-uuid"
          destination_branch: "main"